### PR TITLE
Update calcMap.js

### PR DESCRIPTION
**Pull request by vitaly-t**
you were too fast, i was about to make one necessary correction :)

### CODE REVIEW

**Comment by drewatk** [comment]
@vitaly-t Whoops... Can you explain what's better about your solution?

**Comment by vitaly-t** [comment]
1. You should use a transaction when doing multiple updates
2. You should use methods `map` and `each` to simplify the iteration
3. You should execute mutiple same-type operations within a task/transaction, using method `batch`, or else you risk running out of connections.

See also:
* https://github.com/vitaly-t/pg-promise/wiki/Common-Mistakes#tasks-versus-rootdirect-queries
* https://github.com/vitaly-t/pg-promise/wiki/chaining-queries

**Comment by drewatk** [comment]
I saw that! Thank you so much, I really appreciate your help and explanation.
This is my first venture into postgres =D

**Comment by vitaly-t** [comment]
**Hint:** you will find it a lot more fun, by turning to the use of external SQL files earlier ;)

See:
* http://vitaly-t.github.io/pg-promise/QueryFile.html
* https://github.com/vitaly-t/pg-promise#query-files

**Comment by drewatk** [comment]
Cool, I saw those and figured there would only be a few queries on a single table, but I might make that change soon since it's getting larger.

**Pull request merged**
